### ISSUE TITLE
pylandau.landau

### ISSUE THREAD

**Issue by fmu984** [SiLab-Bonn/pyLandau#5]
Dear David,
according to your renaming I changed the imports in my python scripts to:
`import pylandau`
using `optimize.curve_fit(pylandau.landau` results in a strange fit - anyway but not a landau. Please have a look at the red curve. The green is langau which looks fine.

![figure_1](https://cloud.githubusercontent.com/assets/20536386/16947626/6abd8d78-4db0-11e6-9c3f-d8266b0b037d.png)

**Comment by DavidLP** [comment]
Thank you very much for your bug report. So far oscillations were only observed when the Langaus function was used and the eta / sigma ration was too large (see issue: https://github.com/SiLab-Bonn/pyLandau/issues/1). To see this without convolution is weird. 
Can you tell me the fit results (mu, eta, A) so that I can try to reproduce the error?

**Comment by fmu984** [comment]
Fixed by using more appropriate parameters. Indeed it is the Langau, not Landau.

**Comment by DavidLP** [comment]
That's the difficulty with convolution and and fitting that can create an oscillating solution. To make the fit more stable it is usually good to restrict the parameter range by setting bounds. This is possible with _scipy_ with the bounds parameter:

```
curve_fit(func, xdata, ydata, bounds=(0, [3., 2., 1.]))
```
